server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/code_school?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
mybatis:
  type-aliases-package: com.fyytest.recode_school.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  file:
    name: log/log.log
  level:
    root: info
    fyytest: debug